#include "Services/usb_midi/usb_midi.h"
#include "Services/router/router.h"
#include "Config/module_config.h"

/* Check if USB Device files are available before including them */


#if MODULE_ENABLE_USB_MIDI

#include "usb_device.h"
#include "usbd_midi.h"

/* External USB Device handle (generated by CubeMX) */
extern USBD_HandleTypeDef hUsbDeviceFS;

/* MIDI Interface Callbacks */
static void USBD_MIDI_Init_Callback(void);
static void USBD_MIDI_DeInit_Callback(void);
static void USBD_MIDI_DataOut_Callback(USBD_MIDI_EventPacket_t *packet);

static USBD_MIDI_ItfTypeDef midi_fops = {
  USBD_MIDI_Init_Callback,
  USBD_MIDI_DeInit_Callback,
  USBD_MIDI_DataOut_Callback
};

void usb_midi_init(void) {
  /* Register interface callbacks with USB Device MIDI class */
  USBD_MIDI_RegisterInterface(&hUsbDeviceFS, &midi_fops);
}

void usb_midi_send_packet(uint8_t cin, uint8_t b0, uint8_t b1, uint8_t b2) {
  /* Extract cable number from CIN (upper 4 bits) */
  uint8_t cable = (cin >> 4) & 0x0F;
  
  /* Build MIDI message (without header) */
  uint8_t data[3] = {b0, b1, b2};
  uint16_t length = 3;
  
  /* Adjust length based on message type (like MIOS32) */
  uint8_t status = b0 & 0xF0;
  if (status == 0xC0 || status == 0xD0) {
    length = 2; /* Program Change, Channel Pressure - 2 bytes */
  }
  
  /* Send via USB Device MIDI (4 ports supported) */
  USBD_MIDI_SendData(&hUsbDeviceFS, cable, data, length);
}

void usb_midi_rx_packet(const uint8_t packet4[4]) {
  /* Extract cable number (upper 4 bits of header) - MIOS32 style */
  uint8_t cable = (packet4[0] >> 4) & 0x0F;
  
  /* Route to appropriate router node based on cable number (0-3) */
  router_msg_t msg;
  msg.type = ROUTER_MSG_3B;
  msg.b0 = packet4[1];
  msg.b1 = packet4[2];
  msg.b2 = packet4[3];
  
  /* Map cable 0-3 to USB_PORT0-3 nodes (like MIOS32's USB0-USB3) */
  uint8_t node = ROUTER_NODE_USB_PORT0 + (cable & 0x03);
  router_process(node, &msg);
}

/* Callbacks */
static void USBD_MIDI_Init_Callback(void) {
  /* USB MIDI initialized - all 4 ports ready */
}

static void USBD_MIDI_DeInit_Callback(void) {
  /* USB MIDI de-initialized */
}

static void USBD_MIDI_DataOut_Callback(USBD_MIDI_EventPacket_t *packet) {
  /* Forward packet to application layer (4-byte USB MIDI packet) */
  usb_midi_rx_packet((uint8_t*)packet);
}

#else /* !MODULE_ENABLE_USB_MIDI || !USB_DEVICE_AVAILABLE */

/* Stub implementations when USB Device MIDI is not enabled or USB_DEVICE files don't exist */
void usb_midi_init(void) {
  /* USB Device MIDI not available - either disabled or CubeMX files not generated yet */
}

void usb_midi_send_packet(uint8_t cin, uint8_t b0, uint8_t b1, uint8_t b2) {
  (void)cin; (void)b0; (void)b1; (void)b2;
  /* Stub: USB Device MIDI not enabled or CubeMX files not generated */
}

void usb_midi_rx_packet(const uint8_t packet4[4]) {
  (void)packet4;
  /* Stub: USB Device MIDI not enabled or CubeMX files not generated */
}

#endif /* MODULE_ENABLE_USB_MIDI && USB_DEVICE_AVAILABLE */
