/**
 ******************************************************************************
 * @file    usb_cdc.c
 * @brief   USB CDC (Virtual COM Port / ACM) Service Implementation
 * @author  MidiCore Project
 ******************************************************************************
 * @attention
 *
 * USB CDC ACM service implementation with MIOS32 compatibility
 * Maps between USB_DEVICE/Class/CDC interface and application layer
 * 
 ******************************************************************************
 */

#include "Services/usb_cdc/usb_cdc.h"
#include "Config/module_config.h"
#include <string.h>

#if MODULE_ENABLE_USB_CDC

/* Include USB Device stack and CDC class */
#include "usb_device.h"
#include "USB_DEVICE/Class/CDC/Inc/usbd_cdc.h"
#include "USB_DEVICE/Class/CDC/Inc/usbd_cdc_if.h"

/* External USB Device handle (generated by CubeMX) */
extern USBD_HandleTypeDef hUsbDeviceFS;

/* Private variables */
static usb_cdc_rx_callback_t rx_callback = NULL;
static uint8_t is_initialized = 0;

/* ============================================================================
 * Service API Implementation
 * ============================================================================ */

void usb_cdc_init(void) {
  if (is_initialized) {
    return; /* Already initialized */
  }
  
  /* Register CDC interface callbacks with USB Device stack */
  USBD_CDC_RegisterInterface(&hUsbDeviceFS, &USBD_CDC_fops);
  
  is_initialized = 1;
}

int32_t usb_cdc_send(const uint8_t *buf, uint32_t len) {
  if (!is_initialized) {
    return USB_CDC_NOT_READY;
  }
  
  if (buf == NULL || len == 0) {
    return USB_CDC_ERROR;
  }
  
  /* Check if CDC interface is ready to transmit */
  if (!usb_cdc_is_connected()) {
    return USB_CDC_NOT_READY;
  }
  
  /* Send data via CDC interface */
  uint8_t result = USBD_CDC_TransmitData(&hUsbDeviceFS, (uint8_t*)buf, len);
  
  if (result == USBD_OK) {
    return (int32_t)len; /* Return number of bytes sent */
  } else if (result == USBD_BUSY) {
    return USB_CDC_BUSY;
  } else {
    return USB_CDC_ERROR;
  }
}

void usb_cdc_register_receive_callback(usb_cdc_rx_callback_t callback) {
  rx_callback = callback;
}

uint8_t usb_cdc_is_connected(void) {
  if (!is_initialized) {
    return 0;
  }
  
  /* Check if USB device is configured and CDC interface is ready */
  return USBD_CDC_IsConnected(&hUsbDeviceFS);
}

/* ============================================================================
 * Internal Callbacks (called from usbd_cdc_if.c)
 * ============================================================================ */

/**
 * @brief Internal callback for received CDC data
 * @param buf Pointer to received data buffer
 * @param len Number of bytes received
 * 
 * Called from USB interrupt context via usbd_cdc_if.c
 * Forwards data to registered application callback
 */
void usb_cdc_rx_callback_internal(const uint8_t *buf, uint32_t len) {
  if (rx_callback != NULL) {
    rx_callback(buf, len);
  }
}

#else /* !MODULE_ENABLE_USB_CDC */

/* Stub implementations when CDC is disabled */
void usb_cdc_init(void) {}
int32_t usb_cdc_send(const uint8_t *buf, uint32_t len) { (void)buf; (void)len; return USB_CDC_NOT_READY; }
void usb_cdc_register_receive_callback(usb_cdc_rx_callback_t callback) { (void)callback; }
uint8_t usb_cdc_is_connected(void) { return 0; }
void usb_cdc_rx_callback_internal(const uint8_t *buf, uint32_t len) { (void)buf; (void)len; }

#endif /* MODULE_ENABLE_USB_CDC */
